### ISSUE TITLE
Split the command line and the results 

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#392] opened 2023-10-03 21:50 UTC
Sometimes we have the command line and the result of the command line in the same block code. We should split it so people can easily copy paste the command and not the result

**Comment by holly-cummins** [comment] 2023-10-04 07:28
I think this is a duplicate of #366. I suggest a more complex solution in #366, so I'll copy the pragmatic suggestion over to that one, and we can decide how much time we want to invest. :)

**Closed by holly-cummins** 2023-10-04 07:28 UTC
Labels: documentation
