### ISSUE TITLE
Document the jq installation

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-workshops#391] opened 2023-10-03 21:48 UTC
We should document how to install HQ in the appendix

**Comment by holly-cummins** [comment] 2023-10-04 07:32
I think this is a duplicate of #387 - note that we actually do document it in the appendix at the moment, but that's not very useful ... especially since it's in a section labelled "cURL" :)

**Closed by holly-cummins** 2023-10-04 07:32 UTC
Labels: documentation
